import axios from "axios";
const BaseURL = import.meta.env.VITE_BACKEND_URL;
const api = axios.create({
    baseURL: BaseURL,
    withCredentials: true,
});


/**
 * @description Generate an interview report for a candidate based on their resume, self description and job description
 * @param {*} jobDescription
 * @param {*} selfDescription
 * @param {*} resumeFile
 * @returns Interview report generated by the AI for the candidate based on the provided details
 */
export const generateInterviewReport = async ({ jobDescription, selfDescription, resumeFile }) => {
    const formData = new FormData();
    formData.append("jobDescription", jobDescription);
    formData.append("selfDescription", selfDescription);
    formData.append("resume", resumeFile);
    const response = await api.post("/api/interview/", formData, {
        headers: {
            "Content-Type": "multipart/form-data"
        }
    });
    return response.data;
}


/**
 * @description Get the interview report for a specific interview
 * @param {*} interviewId 
 * @returns Interview report for the specified interview ID
 */
export const getInterviewReportById = async (interviewId) => {
    const response = await api.get(`/api/interview/report/${interviewId}`);
    return response.data;
};


/**
 * @description Get all interview reports for the authenticated user
 * @returns List of all interview reports for the authenticated user
 */
export const getAllInterviewReports = async () => {
    const response = await api.get("/api/interview/");
    return response.data;
};

export const generateResumePDF = async (interviewId) => {
    const response = await api.get(`/api/interview/resume/pdf/${interviewId}`, {
        responseType: 'blob'
    });
    return response.data;
};